name: "Notify Action"
description: "Notify is a helper utility written in Go that allows you to post output to multiple platforms."
branding:
  icon: "activity"
  color: "blue"

inputs:
  data:
    description: "Input file to send with notify"
    required: false

  config:
    description: "Config file to use with notify"
    required: false

  flags:
    description: "Additional notify CLI flags to use"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/notify ] && GO111MODULE=on go get -v github.com/projectdiscovery/notify/cmd/notify@v0.0.2
        [ ! -z ${{ inputs.data }} ] && echo "data=< ${{ inputs.data}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.config }} ] && mkdir -p /home/runner/.config/notify/ && cp ${{ inputs.config }} /home/runner/.config/notify/notify.conf
        [ ! -z ${{ inputs.flags }} ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        notify \
          ${{ env.config }} \
          ${{ env.flags }} \
          ${{ env.data }}
      shell: bash
